root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/api"  # Updated to point to cmd/api
  delay = 1000
exclude_dir = ["client", "assets", "tmp", "vendor", "node_modules", "frontend/node_modules", ".git", "dist", "build", "coverage", ".vscode", ".idea", "logs", "bin", "testdata"]
  exclude_file = [".env", ".env.*", "*.md", "*.log", "*.sum", "*.mod", "*.test", "*.out", ".gitignore", ".air.toml", "LICENSE", "README*", "Dockerfile*", "docker-compose*", ".dockerignore", "*.exe", "*.dll", "*.so", "*.dylib"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
