definitions:
  database.Todo:
    properties:
      completed:
        example: false
        type: boolean
      createdAt:
        example: "2025-05-20T14:28:23Z"
        type: string
      description:
        example: Milk, eggs, and bread
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      title:
        example: Buy groceries
        type: string
      userId:
        example: user-abc-123
        type: string
    type: object
  database.TodoCreate:
    properties:
      description:
        example: Schedule annual check-up
        type: string
      title:
        example: Call the doctor
        minLength: 3
        type: string
    required:
    - title
    type: object
  database.TodoPatch:
    properties:
      completed:
        example: true
        type: boolean
      description:
        example: Ask about whitening treatment
        type: string
      title:
        example: Call the dentist
        minLength: 3
        type: string
    type: object
  main.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: secret123
        type: string
    type: object
  main.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      name:
        example: Jane Doe
        type: string
      password:
        example: secret123
        type: string
    type: object
info:
  contact: {}
  description: A simple Go web API for managing todos.
  title: Go Web API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token for future requests.
      parameters:
      - description: User login payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Logs in a user
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Creates a user account with email, password, and name
      parameters:
      - description: User registration payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Registers a new user
      tags:
      - auth
  /api/v1/todos:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all todos for the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Todo'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Adds a new todo for the authenticated user.
      parameters:
      - description: Todo object
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/database.TodoCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/database.Todo'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create a new todo
      tags:
      - todos
  /api/v1/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the todo with the specified ID.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete a todo
      tags:
      - todos
    patch:
      consumes:
      - application/json
      description: Updates the fields of a todo identified by ID.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      - description: Todo object
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/database.TodoPatch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Todo'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update a todo
      tags:
      - todos
produces:
- application/json
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Enter your bearer token in the format "Bearer <token>".
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
